sudo: false
language: ruby
rvm:
  - 2.2.4
services:
  - mysql
before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database tasafo_jobs_test;'
  - bundle exec rake db:migrate RAILS_ENV=test
script: xvfb-run -a bundle exec rspec
addons:
  apt:
    packages:
      - libqtwebkit-dev
      - xvfb
  code_climate:
    repo_token: 86bbdf4badf3f08a454c1022696446d17801aca331013de524773c7b117f2b71
