# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebf6f19bad90ec6c79a63559a90012fb608435da3aeae0fd529daaf80e55606fe5405bba22d8201155fd38a6f1dcef391c5751de34f8faf25e567e5a26d00ae9

test:
  secret_key_base: fc93e126c5cde5d193c714a7c95ba1b59293c7f61cb44ffb7bcdf3e190032bf2e66bf169955a045851ea2f6de2b97f39609b19a9a6d4b0512331539045957bd6 

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
